caught ValueError from downstream
[1, 2]
